name: reaper
base: core18 # the base snap is the execution environment for this snap
version: '669' # just for humans, typically '1.2+git' or '1.3.2'
summary: Reaper
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: i386
  - build-on: amd64

parts:
  reaper:
    plugin: dump
    source: 
      - on amd64: http://reaper.fm/files/6.x/reaper$SNAPCRAFT_PROJECT_VERSION_linux_x86_64.tar.xz
      - on i386: http://reaper.fm/files/6.x/reaper$SNAPCRAFT_PROJECT_VERSION_linux_i686.tar.xz
    stage-packages:
      - libpulse0
      - jackd1

apps:
  reaper:
    extensions: [gnome-3-28]
    command: reaper
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH
    plugs:
      - audio-playback
      - audio-record
      - x11
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - jack1
